name: Auto-label Documentation Update Issues

on:
  issues:
    types:
      - opened

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Extract issue body
        id: extract_body
        uses: actions/github-script@v7
        with:
          script: |
            const issueBody = context.payload.issue.body;
            return issueBody;

      - name: Determine labels
        id: determine_labels
        run: |
          LABELS=""
          FLAT_ISSUE_BODY=$(echo "${{ steps.extract_body.outputs.result }}" | tr '\n' ' ')
          case "$FLAT_ISSUE_BODY" in
            *"- [x] Alloy"*) LABELS="$LABELS Alloy" ;;
            *"- [x] Blueprint"*) LABELS="$LABELS Blueprint" ;;
            *"- [x] Caster"*) LABELS="$LABELS Caster" ;;
            *"- [x] CITE"*) LABELS="$LABELS CITE" ;;
            *"- [x] Gallery"*) LABELS="$LABELS Gallery" ;;
            *"- [x] Gameboard"*) LABELS="$LABELS Gameboard" ;;
            *"- [x] Player"*) LABELS="$LABELS Player" ;;
            *"- [x] Steamfitter"*) LABELS="$LABELS Steamfitter" ;;
            *"- [x] TopoMojo"*) LABELS="$LABELS TopoMojo" ;;
            *"- [x] General Docs Update"*) LABELS="$LABELS General Docs Update" ;;
            *"- [x] New feature"*) LABELS="$LABELS New feature" ;;
            *"- [x] Correction"*) LABELS="$LABELS Correction" ;;
            *"- [x] Enhancement"*) LABELS="$LABELS Enhancement" ;;
            *"- [x] Other"*) LABELS="$LABELS Other" ;;
          esac
          echo "LABELS=$(echo $LABELS | xargs)" >> $GITHUB_ENV

      - name: Add labels to issue
        uses: actions/github-script@v7
        with:
          script: |
            const labels = process.env.LABELS.split(' ');
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: labels
            });
